spring:
  data:
    neo4j:
      uri: bolt://127.0.0.1:32772
      username: neo4j
      password: password
  jackson:
    property-naming-strategy: SNAKE_CASE
  rabbitmq:
    host: 127.0.0.1
    port: 32773

mq:
  application: springboot-neo4j-api
  exchange: apis.direct
  in-queue-name: mongodb.queue
  out-queue-key: neo4j.key

logging:
  level:
    root: INFO